//go:build ignore

package main

import (
	"fmt"
	"os"
)

func main() {
	content, err := os.ReadFile("../../../llms.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading llms.txt: %v\n", err)
		os.Exit(1)
	}

	out, err := os.Create("llms_content.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by gen_llms.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(out, "package cmd\n\n")
	fmt.Fprintf(out, "const llmsTxt = %q\n", string(content))
}
