version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - (io.Closer).Close
        - (*os.File).Close
    staticcheck:
      checks:
        - "all"
        - "-QF1001"
        - "-QF1003"
  exclusions:
    rules:
      - linters:
          - errcheck
        source: "defer.*\\.Close\\(\\)"
