version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: hitspec
    main: ./apps/cli
    binary: hitspec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/hitspec/apps/cli/cmd.version={{.Version}}
      - -X github.com/abdul-hamid-achik/hitspec/apps/cli/cmd.commit={{.Commit}}
      - -X github.com/abdul-hamid-achik/hitspec/apps/cli/cmd.date={{.Date}}

archives:
  - id: hitspec
    builds:
      - hitspec
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: abdul-hamid-achik
    name: hitspec
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: hitspec
    repository:
      owner: abdul-hamid-achik
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/abdul-hamid-achik/hitspec"
    description: "Plain text API tests. No magic."
    license: "MIT"
    install: |
      bin.install "hitspec"
    test: |
      system "#{bin}/hitspec", "version"
    skip_upload: "{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}"
