version: '3'

vars:
  BINARY_NAME: hitspec
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  LDFLAGS: -ldflags "-X main.version={{.VERSION}} -X main.buildTime={{.BUILD_TIME}}"
  MAIN_PATH: ./apps/cli

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the CLI binary
    cmds:
      - go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}} {{.MAIN_PATH}}
    sources:
      - '**/*.go'
    generates:
      - bin/{{.BINARY_NAME}}

  install:
    desc: Install the CLI to GOPATH/bin
    cmds:
      - go install {{.LDFLAGS}} {{.MAIN_PATH}}

  test:
    desc: Run all tests
    cmds:
      - go test -v -race -cover ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:unit:
    desc: Run unit tests only
    cmds:
      - go test -v -race -short ./...

  test:integration:
    desc: Run integration tests
    cmds:
      - go test -v -race -run Integration ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  run:
    desc: Run the CLI (use -- to pass args, e.g., task run -- run examples/simple.http)
    cmds:
      - go run {{.MAIN_PATH}} {{.CLI_ARGS}}

  dev:
    desc: Run in development mode with example file
    cmds:
      - go run {{.MAIN_PATH}} run examples/petstore/petstore.http -v

  watch:
    desc: Watch for changes and re-run tests
    cmds:
      - watchexec -e go -r -- go test -v ./...

  watch:run:
    desc: Watch for changes and re-run CLI
    cmds:
      - watchexec -e go,http -r -- go run {{.MAIN_PATH}} run examples/petstore/petstore.http -v

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  deps:update:
    desc: Update all dependencies
    cmds:
      - go get -u ./...
      - go mod tidy

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  build:all:
    desc: Build for all platforms
    cmds:
      - GOOS=linux GOARCH=amd64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PATH}}
      - GOOS=linux GOARCH=arm64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-linux-arm64 {{.MAIN_PATH}}
      - GOOS=darwin GOARCH=amd64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PATH}}
      - GOOS=darwin GOARCH=arm64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-darwin-arm64 {{.MAIN_PATH}}
      - GOOS=windows GOARCH=amd64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-windows-amd64.exe {{.MAIN_PATH}}

  release:snapshot:
    desc: Create a snapshot release (no publishing)
    cmds:
      - goreleaser release --snapshot --clean

  release:
    desc: Create and publish a release
    cmds:
      - goreleaser release --clean

  docs:serve:
    desc: Serve documentation locally
    cmds:
      - echo "Starting docs server at http://localhost:8000"
      - python3 -m http.server 8000 --directory docs

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  bench:
    desc: Run benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  bench:parser:
    desc: Run parser benchmarks
    cmds:
      - go test -bench=. -benchmem ./packages/core/parser/...

  security:
    desc: Run security checks
    cmds:
      - gosec ./...
      - govulncheck ./...
