// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package history

import (
	"database/sql"
	"time"
)

type Assertion struct {
	ID       int64
	ResultID int64
	Operator string
	Subject  string
	Expected sql.NullString
	Actual   sql.NullString
	Passed   bool
	Message  sql.NullString
}

type Result struct {
	ID          int64
	RunID       int64
	RequestName string
	Method      string
	Url         string
	StatusCode  sql.NullInt64
	DurationMs  int64
	Passed      bool
	Skipped     bool
	Error       sql.NullString
	Description sql.NullString
	BodyPreview sql.NullString
	CreatedAt   time.Time
}

type Run struct {
	ID          int64
	FilePath    string
	Environment sql.NullString
	StartedAt   time.Time
	FinishedAt  sql.NullTime
	DurationMs  int64
	Passed      int64
	Failed      int64
	Skipped     int64
	Total       int64
}
