// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package history

import (
	"context"
	"database/sql"
	"time"
)

const clearAllRuns = `-- name: ClearAllRuns :exec
DELETE FROM runs
`

func (q *Queries) ClearAllRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllRuns)
	return err
}

const countRuns = `-- name: CountRuns :one
SELECT COUNT(*) FROM runs
`

func (q *Queries) CountRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM runs WHERE id = ?
`

func (q *Queries) DeleteRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRun, id)
	return err
}

const deleteRunsBefore = `-- name: DeleteRunsBefore :exec
DELETE FROM runs WHERE started_at < ?
`

func (q *Queries) DeleteRunsBefore(ctx context.Context, startedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteRunsBefore, startedAt)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, file_path, environment, started_at, finished_at, duration_ms, passed, failed, skipped, total FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Environment,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Passed,
		&i.Failed,
		&i.Skipped,
		&i.Total,
	)
	return i, err
}

const insertAssertion = `-- name: InsertAssertion :exec
INSERT INTO assertions (result_id, operator, subject, expected, actual, passed, message)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAssertionParams struct {
	ResultID int64
	Operator string
	Subject  string
	Expected sql.NullString
	Actual   sql.NullString
	Passed   bool
	Message  sql.NullString
}

func (q *Queries) InsertAssertion(ctx context.Context, arg InsertAssertionParams) error {
	_, err := q.db.ExecContext(ctx, insertAssertion,
		arg.ResultID,
		arg.Operator,
		arg.Subject,
		arg.Expected,
		arg.Actual,
		arg.Passed,
		arg.Message,
	)
	return err
}

const insertResult = `-- name: InsertResult :one
INSERT INTO results (run_id, request_name, method, url, status_code, duration_ms, passed, skipped, error, description, body_preview)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, request_name, method, url, status_code, duration_ms, passed, skipped, error, description, body_preview, created_at
`

type InsertResultParams struct {
	RunID       int64
	RequestName string
	Method      string
	Url         string
	StatusCode  sql.NullInt64
	DurationMs  int64
	Passed      bool
	Skipped     bool
	Error       sql.NullString
	Description sql.NullString
	BodyPreview sql.NullString
}

func (q *Queries) InsertResult(ctx context.Context, arg InsertResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, insertResult,
		arg.RunID,
		arg.RequestName,
		arg.Method,
		arg.Url,
		arg.StatusCode,
		arg.DurationMs,
		arg.Passed,
		arg.Skipped,
		arg.Error,
		arg.Description,
		arg.BodyPreview,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RequestName,
		&i.Method,
		&i.Url,
		&i.StatusCode,
		&i.DurationMs,
		&i.Passed,
		&i.Skipped,
		&i.Error,
		&i.Description,
		&i.BodyPreview,
		&i.CreatedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (file_path, environment)
VALUES (?, ?)
RETURNING id, file_path, environment, started_at, finished_at, duration_ms, passed, failed, skipped, total
`

type InsertRunParams struct {
	FilePath    string
	Environment sql.NullString
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, insertRun, arg.FilePath, arg.Environment)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Environment,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Passed,
		&i.Failed,
		&i.Skipped,
		&i.Total,
	)
	return i, err
}

const listAssertionsByResult = `-- name: ListAssertionsByResult :many
SELECT id, result_id, operator, subject, expected, actual, passed, message FROM assertions WHERE result_id = ? ORDER BY id
`

func (q *Queries) ListAssertionsByResult(ctx context.Context, resultID int64) ([]Assertion, error) {
	rows, err := q.db.QueryContext(ctx, listAssertionsByResult, resultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assertion
	for rows.Next() {
		var i Assertion
		if err := rows.Scan(
			&i.ID,
			&i.ResultID,
			&i.Operator,
			&i.Subject,
			&i.Expected,
			&i.Actual,
			&i.Passed,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsByRun = `-- name: ListResultsByRun :many
SELECT id, run_id, request_name, method, url, status_code, duration_ms, passed, skipped, error, description, body_preview, created_at FROM results WHERE run_id = ? ORDER BY id
`

func (q *Queries) ListResultsByRun(ctx context.Context, runID int64) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, listResultsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RequestName,
			&i.Method,
			&i.Url,
			&i.StatusCode,
			&i.DurationMs,
			&i.Passed,
			&i.Skipped,
			&i.Error,
			&i.Description,
			&i.BodyPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, file_path, environment, started_at, finished_at, duration_ms, passed, failed, skipped, total FROM runs ORDER BY started_at DESC LIMIT ? OFFSET ?
`

type ListRunsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Environment,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Passed,
			&i.Failed,
			&i.Skipped,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunFinished = `-- name: UpdateRunFinished :exec
UPDATE runs
SET finished_at = ?, duration_ms = ?, passed = ?, failed = ?, skipped = ?, total = ?
WHERE id = ?
`

type UpdateRunFinishedParams struct {
	FinishedAt sql.NullTime
	DurationMs int64
	Passed     int64
	Failed     int64
	Skipped    int64
	Total      int64
	ID         int64
}

func (q *Queries) UpdateRunFinished(ctx context.Context, arg UpdateRunFinishedParams) error {
	_, err := q.db.ExecContext(ctx, updateRunFinished,
		arg.FinishedAt,
		arg.DurationMs,
		arg.Passed,
		arg.Failed,
		arg.Skipped,
		arg.Total,
		arg.ID,
	)
	return err
}
